[project]
name = "pp3d"
version = "0.2.0"
description = "A Python-based research and experimental framework for 3D path planning with terrain awareness, including algorithms, simulation, and interactive visualization."
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "codeboyzhou", email="zhouchen9118@foxmail.com" }
]
maintainers = [
    { name = "codeboyzhou", email="zhouchen9118@foxmail.com" }
]
keywords = ["3d", "path-planning", "PSO", "GA", "algorithm", "playground"]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License"
]
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "pydantic>=2.12.3",
    "scipy>=1.16.3",
    "streamlit>=1.51.0",
    "streamlit-ace>=0.1.1",
]

[project.urls]
Homepage = "https://github.com/codeboyzhou/PathPlanner3D"
Repository = "https://github.com/codeboyzhou/PathPlanner3D.git"
Issues = "https://github.com/codeboyzhou/PathPlanner3D/issues"
Documentation = "https://github.com/codeboyzhou/PathPlanner3D/blob/main/README.md"

[dependency-groups]
dev = [
    "build>=1.3.0",
    "hatchling>=1.27.0",
    "pandas-stubs>=2.3.2.250926",
    "pre-commit>=4.3.0",
    "pyright>=1.1.407",
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "pytest-html>=4.1.1",
    "ruff>=0.14.3",
    "scipy-stubs>=1.16.3.0",
    "twine>=6.2.0",
]

[tool.ruff]
line-length = 120
target-version = "py312"
extend-exclude = ["README.md"]

[tool.ruff.lint]
select = ["C4", "E", "F", "I", "PERF", "UP"]
ignore = ["PERF203"]

[tool.pytest.ini_options]
testpaths = ["tests/unittests"]
addopts = """
--cov=src/pp3d/algorithm
--cov=src/pp3d/algorithm/genetic
--cov=src/pp3d/algorithm/hybrid
--cov=src/pp3d/algorithm/pso
--cov=src/pp3d/common
--cov=src/pp3d/playground
--cov=src/pp3d/visualization
--cov-report=term
--cov-report=html
--cov-report=xml
--html=pytest/report.html
"""

[tool.coverage.run]
branch = true
source = ["src/pp3d"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pp3d"]
